[features]
seeds = false
skip-lint = false
[programs.localnet]
amm_tutorial = "CUPMV4NGFSBQcjbPfZZJodNLkzfBUyjobW6Fg8E4fF7s"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/julien/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
